### PR TITLE
fixed dockerfile

### PR DESCRIPTION
**Pull request by dhaneshragu**
# Solves Issue #1 
- Changed the Dockerfile so as to install all required puppeteer packages

### CODE REVIEW

**Comment by GeekyPS** [comment]
the PR has some merge conflicts with the main. , fix them in further commit

**Comment by GeekyPS** [comment]
minor issues regarding to the generated screenshots , I suggest to add them to .gitignore

**Comment by GeekyPS** [comment]
moreover on further PR make sure to pull latest upstream then make changes, since the repo is in active modifications

**Comment by dhaneshragu** [comment]
@GeekyPS resolved the merge conflicts

**Pull request merged**
